version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: always

  api:
    build: .
    ports:
      - "8080:${PORT}"
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./api/:/app